version: '3.3'

networks:
  simpleapi:

services:
  simpleapi:
    image: nginx:stable-alpine
    container_name: nginx-simpleapi
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - simpleapi

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-simpleapi
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - simpleapi

  composer:
    image: composer:latest
    container_name: composer-simpleapi
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - simpleapi